Repository logstash-plugins/logstash-output-elasticsearch, pull requests merged in 2018-03, with the labels that each got.

#744 Fix typo "elasticseach’s" => "elasticsearch’s"
  docs/index.asciidoc
Labels: docs

#743 Update index.asciidoc
  docs/index.asciidoc
Labels: docs

#741 Set number_of_shards to 1
  lib/logstash/outputs/elasticsearch/elasticsearch-template-es7x.json
Labels: enhancement

#585 add a few metrics to the plugin
  lib/logstash/outputs/elasticsearch.rb
  lib/logstash/outputs/elasticsearch/common.rb
  lib/logstash/outputs/elasticsearch/http_client.rb
  lib/logstash/outputs/elasticsearch/http_client/pool.rb
  lib/logstash/outputs/elasticsearch/http_client_builder.rb
  spec/integration/outputs/metrics_spec.rb
  spec/integration/outputs/sniffer_spec.rb
  spec/unit/outputs/elasticsearch/http_client_spec.rb
Labels: enhancement

#747 assume document type is _doc for ES 7.x clusters
  lib/logstash/outputs/elasticsearch/common.rb
  spec/unit/outputs/elasticsearch_spec.rb
Labels: bug

#749 Fix incorrect logging of non-SafeURI as BadResponseCode
  lib/logstash/outputs/elasticsearch/http_client.rb
Labels: bug

#754 Add an example for "script" option in documentation
  docs/index.asciidoc
Labels: docs
