Repository logstash-plugins/logstash-output-elasticsearch, pull requests merged in 2021-11, with the labels that each got.

#1047 ecs: update v1 to ECS v1.12.1
  CHANGELOG.md
  Rakefile
  logstash-output-elasticsearch.gemspec
Labels: status:approved

#1049 ecs: pin v1 to upstream's v1.10.0 to avoid pulling breaking field types
  .ci/Dockerfile.elasticsearch
  .travis.yml
  CHANGELOG.md
  Rakefile
  logstash-output-elasticsearch.gemspec
Labels: status:approved

#1048 ECS templates for elasticsearch 8
  CHANGELOG.md
  Rakefile
  lib/logstash/outputs/elasticsearch.rb
  logstash-output-elasticsearch.gemspec
  spec/integration/outputs/templates_spec.rb
  spec/unit/outputs/elasticsearch/template_manager_spec.rb
Labels: status:approved

#1046 Data streams require ECS
  CHANGELOG.md
  lib/logstash/outputs/elasticsearch.rb
  lib/logstash/outputs/elasticsearch/data_stream_support.rb
  logstash-output-elasticsearch.gemspec
  spec/integration/outputs/data_stream_spec.rb
  spec/unit/outputs/elasticsearch/data_stream_support_spec.rb
  spec/unit/outputs/elasticsearch_spec.rb
Labels: discuss, status:approved

#1051 Add PR/issue links to changelog
  CHANGELOG.md
Labels: status:approved

#1053 Doc: Fix note format
  docs/index.asciidoc
Labels: docs
