Repository logstash-plugins/logstash-output-elasticsearch, pull requests merged in 2021-04, with the labels that each got.

#972 fix: prevent sub-batch 413's from blocking whole batch
  .ci/elasticsearch-run.sh
  CHANGELOG.md
  lib/logstash/outputs/elasticsearch/http_client.rb
  lib/logstash/plugin_mixins/elasticsearch/common.rb
  logstash-output-elasticsearch.gemspec
  spec/unit/outputs/elasticsearch/http_client_spec.rb
  spec/unit/outputs/elasticsearch_spec.rb
Labels: int-shortlist, status:approved

#988 Feat: data-stream support + logging improvements
  CHANGELOG.md
  docs/index.asciidoc
  lib/logstash/outputs/elasticsearch.rb
  lib/logstash/outputs/elasticsearch/data_stream_support.rb
  lib/logstash/outputs/elasticsearch/http_client.rb
  lib/logstash/outputs/elasticsearch/http_client/pool.rb
  lib/logstash/outputs/elasticsearch/ilm.rb
  lib/logstash/outputs/elasticsearch/template_manager.rb
  lib/logstash/plugin_mixins/elasticsearch/api_configs.rb
  lib/logstash/plugin_mixins/elasticsearch/common.rb
  logstash-output-elasticsearch.gemspec
  spec/es_spec_helper.rb
  spec/integration/outputs/data_stream_spec.rb
  spec/integration/outputs/ilm_spec.rb
  spec/integration/outputs/ingest_pipeline_spec.rb
  spec/integration/outputs/retry_spec.rb
  spec/integration/outputs/sniffer_spec.rb
  spec/spec_helper.rb
  spec/unit/outputs/elasticsearch/data_stream_support_spec.rb
  spec/unit/outputs/elasticsearch/http_client/manticore_adapter_spec.rb
  spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
  spec/unit/outputs/elasticsearch/http_client_spec.rb
  spec/unit/outputs/elasticsearch/template_manager_spec.rb
  spec/unit/outputs/elasticsearch_proxy_spec.rb
  spec/unit/outputs/elasticsearch_spec.rb
  spec/unit/outputs/elasticsearch_ssl_spec.rb
  spec/unit/outputs/error_whitelist_spec.rb
Labels: status:approved

#1005 Feat: always check ES license
  .travis.yml
  CHANGELOG.md
  lib/logstash/outputs/elasticsearch/license_checker.rb
  logstash-output-elasticsearch.gemspec
  spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
  spec/unit/outputs/license_check_spec.rb
Labels: status:approved

#1011 Doc: Fixed list item to address broken link
  CHANGELOG.md
  docs/index.asciidoc
  logstash-output-elasticsearch.gemspec
Labels: docs, status:approved

#1012 Fix: DLQ expects us to pass down an event
  CHANGELOG.md
  lib/logstash/outputs/elasticsearch.rb
  lib/logstash/outputs/elasticsearch/data_stream_support.rb
  lib/logstash/plugin_mixins/elasticsearch/common.rb
  spec/unit/outputs/elasticsearch_spec.rb
Labels: status:approved
