Repository logstash-plugins/logstash-output-elasticsearch, pull requests merged in 2022-09, with the labels that each got.

#1067 Adds a new `dlq_custom_codes` option to customize DLQ codes
  CHANGELOG.md
  docs/index.asciidoc
  lib/logstash/outputs/elasticsearch.rb
  lib/logstash/plugin_mixins/elasticsearch/common.rb
  logstash-output-elasticsearch.gemspec
  spec/unit/outputs/elasticsearch_spec.rb
Labels: enhancement, status:approved

#1084 Route badly interpolated dynamic index to DLQ
  CHANGELOG.md
  docs/index.asciidoc
  lib/logstash/outputs/elasticsearch.rb
  lib/logstash/plugin_mixins/elasticsearch/common.rb
  logstash-output-elasticsearch.gemspec
  spec/integration/outputs/index_spec.rb
  spec/unit/outputs/elasticsearch_spec.rb
Labels: enhancement, status:changes-requested

#1080 Validate the action before sending the bulk request to ES.
  CHANGELOG.md
  README.md
  docs/index.asciidoc
  lib/logstash/outputs/elasticsearch.rb
  lib/logstash/outputs/elasticsearch/http_client.rb
  lib/logstash/plugin_mixins/elasticsearch/common.rb
  logstash-output-elasticsearch.gemspec
  spec/integration/outputs/index_spec.rb
  spec/integration/outputs/unsupported_actions_spec.rb
  spec/unit/outputs/elasticsearch/http_client_spec.rb
  spec/unit/outputs/elasticsearch_spec.rb
Labels: bug, status:changes-requested

#1085 Fix broken link to Logstash Reference
  CHANGELOG.md
  docs/index.asciidoc
  logstash-output-elasticsearch.gemspec
Labels: docs

#1091 Doc: Clarify wording on action option
  docs/index.asciidoc
Labels: docs
