Repository logstash-plugins/logstash-output-elasticsearch, pull requests merged in 2023-11, with the labels that each got.

#1159 Replace document_already_exist_exception with version_conflict_engine_exception in the silence_errors_in_log setting example
  CHANGELOG.md
  docs/index.asciidoc
  lib/logstash/plugin_mixins/elasticsearch/api_configs.rb
  logstash-output-elasticsearch.gemspec
  spec/unit/outputs/error_whitelist_spec.rb
Labels: status:needs-review

#1155 Use integration metadata to create ES actions
  CHANGELOG.md
  lib/logstash/outputs/elasticsearch.rb
  logstash-output-elasticsearch.gemspec
  spec/unit/outputs/elasticsearch_spec.rb
Labels: enhancement, status:approved

#1158 Use integration metadata to create ES actions (part 2)
  CHANGELOG.md
  lib/logstash/outputs/elasticsearch.rb
  logstash-output-elasticsearch.gemspec
  spec/unit/outputs/elasticsearch_spec.rb
Labels: enhancement, status:approved

#1161 When datastream is enabled then no version related attributes fills into document actions
  CHANGELOG.md
  lib/logstash/outputs/elasticsearch.rb
  logstash-output-elasticsearch.gemspec
  spec/unit/outputs/elasticsearch_spec.rb
Labels: bug, status:approved
