Repository logstash-plugins/logstash-output-elasticsearch, pull requests merged in 2023-04, with the labels that each got.

#1119 Check pipeline shutdown status while waiting for valid connection or while issuing a bulk to ES
  CHANGELOG.md
  lib/logstash/outputs/elasticsearch.rb
  lib/logstash/plugin_mixins/elasticsearch/common.rb
  logstash-output-elasticsearch.gemspec
  spec/unit/outputs/elasticsearch_spec.rb
Labels: enhancement, status:approved

#1125 move async finish_register to bottom of register to avoid race condition
  CHANGELOG.md
  lib/logstash/outputs/elasticsearch.rb
  logstash-output-elasticsearch.gemspec
  spec/unit/outputs/elasticsearch_spec.rb
Labels: status:approved

#1105 dlq-logging: reintroduce structured payload where possible
  CHANGELOG.md
  lib/logstash/outputs/elasticsearch.rb
  lib/logstash/plugin_mixins/elasticsearch/common.rb
  spec/es_spec_helper.rb
  spec/integration/outputs/templates_spec.rb
  spec/unit/outputs/elasticsearch_spec.rb
Labels: status:approved

#1128 actual version bump :facepalm:
  logstash-output-elasticsearch.gemspec
Labels: status:needs-review
