Repository logstash-plugins/logstash-output-elasticsearch, pull requests merged in 2023-02, with the labels that each got.

#1114 Bump version to release latest changes
  CHANGELOG.md
  logstash-output-elasticsearch.gemspec
Labels: status:needs-review

#1113 Add support for pipeline to decode from metadata target_ingest_pipeline
  CHANGELOG.md
  docs/index.asciidoc
  lib/logstash/outputs/elasticsearch.rb
  logstash-output-elasticsearch.gemspec
  spec/unit/outputs/elasticsearch_spec.rb
Labels: status:approved

#1102 Resolve ILM settings based loaded template or/and `template_api`
  CHANGELOG.md
  lib/logstash/outputs/elasticsearch/template_manager.rb
  logstash-output-elasticsearch.gemspec
  spec/unit/outputs/elasticsearch/template_manager_spec.rb
Labels: status:changes-requested
